### ISSUE TITLE
prettier pre-commit archived - find alternative

### ISSUE THREAD

**Issue by jazzlyn** [tyriis/home-ops#3907]
archived: https://github.com/pre-commit/mirrors-prettier

find alternative/fork
f.e. https://github.com/rbubley/mirrors-prettier

**Comment by tyriis** [comment]
it is still part of megalinter, so maybe just remove the hook, or switch over to the fork, basically it is working well, only problem there will be no prettier update

**Comment by jazzlyn** [comment]
replaced
