### ISSUE TITLE
evaluate external dns with cloudflare

### ISSUE THREAD

**Issue by tyriis** [tyriis/home-ops#398]

**Comment by jazzlyn** [comment]
Goal: have some apps public available

* https://github.com/kubernetes-sigs/external-dns
* https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md

**Comment by tyriis** [comment]
setup is done external dns + cloudflared is in place to expose ingress routes via cloudflare tunnels
